// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sdmxdl_grpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Sdmxdl.Grpc {
  public static partial class SdmxWebManager
  {
    static readonly string __ServiceName = "sdmxdl.grpc.SdmxWebManager";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Grpc.EmptyDto> __Marshaller_sdmxdl_grpc_EmptyDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Grpc.EmptyDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Format.Protobuf.AboutDto> __Marshaller_sdmxdl_format_protobuf_AboutDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Format.Protobuf.AboutDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Format.Protobuf.Web.WebSourceDto> __Marshaller_sdmxdl_format_protobuf_web_WebSourceDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Format.Protobuf.Web.WebSourceDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Grpc.SourceRequestDto> __Marshaller_sdmxdl_grpc_SourceRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Grpc.SourceRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto> __Marshaller_sdmxdl_format_protobuf_web_MonitorReportDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Format.Protobuf.DatabaseDto> __Marshaller_sdmxdl_format_protobuf_DatabaseDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Format.Protobuf.DatabaseDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Grpc.DatabaseRequestDto> __Marshaller_sdmxdl_grpc_DatabaseRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Grpc.DatabaseRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Format.Protobuf.FlowDto> __Marshaller_sdmxdl_format_protobuf_FlowDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Format.Protobuf.FlowDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Grpc.FlowRequestDto> __Marshaller_sdmxdl_grpc_FlowRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Grpc.FlowRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Format.Protobuf.MetaSetDto> __Marshaller_sdmxdl_format_protobuf_MetaSetDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Format.Protobuf.MetaSetDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Grpc.KeyRequestDto> __Marshaller_sdmxdl_grpc_KeyRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Grpc.KeyRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Format.Protobuf.DataSetDto> __Marshaller_sdmxdl_format_protobuf_DataSetDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Format.Protobuf.DataSetDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Format.Protobuf.SeriesDto> __Marshaller_sdmxdl_format_protobuf_SeriesDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Format.Protobuf.SeriesDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Grpc.KeyDimensionRequestDto> __Marshaller_sdmxdl_grpc_KeyDimensionRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Grpc.KeyDimensionRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sdmxdl.Grpc.DimensionCodesDto> __Marshaller_sdmxdl_grpc_DimensionCodesDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sdmxdl.Grpc.DimensionCodesDto.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.EmptyDto, global::Sdmxdl.Format.Protobuf.AboutDto> __Method_GetAbout = new grpc::Method<global::Sdmxdl.Grpc.EmptyDto, global::Sdmxdl.Format.Protobuf.AboutDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAbout",
        __Marshaller_sdmxdl_grpc_EmptyDto,
        __Marshaller_sdmxdl_format_protobuf_AboutDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.EmptyDto, global::Sdmxdl.Format.Protobuf.Web.WebSourceDto> __Method_GetSources = new grpc::Method<global::Sdmxdl.Grpc.EmptyDto, global::Sdmxdl.Format.Protobuf.Web.WebSourceDto>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetSources",
        __Marshaller_sdmxdl_grpc_EmptyDto,
        __Marshaller_sdmxdl_format_protobuf_web_WebSourceDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.SourceRequestDto, global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto> __Method_GetMonitorReport = new grpc::Method<global::Sdmxdl.Grpc.SourceRequestDto, global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMonitorReport",
        __Marshaller_sdmxdl_grpc_SourceRequestDto,
        __Marshaller_sdmxdl_format_protobuf_web_MonitorReportDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.SourceRequestDto, global::Sdmxdl.Format.Protobuf.DatabaseDto> __Method_GetDatabases = new grpc::Method<global::Sdmxdl.Grpc.SourceRequestDto, global::Sdmxdl.Format.Protobuf.DatabaseDto>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetDatabases",
        __Marshaller_sdmxdl_grpc_SourceRequestDto,
        __Marshaller_sdmxdl_format_protobuf_DatabaseDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.DatabaseRequestDto, global::Sdmxdl.Format.Protobuf.FlowDto> __Method_GetFlows = new grpc::Method<global::Sdmxdl.Grpc.DatabaseRequestDto, global::Sdmxdl.Format.Protobuf.FlowDto>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetFlows",
        __Marshaller_sdmxdl_grpc_DatabaseRequestDto,
        __Marshaller_sdmxdl_format_protobuf_FlowDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.FlowRequestDto, global::Sdmxdl.Format.Protobuf.MetaSetDto> __Method_GetMeta = new grpc::Method<global::Sdmxdl.Grpc.FlowRequestDto, global::Sdmxdl.Format.Protobuf.MetaSetDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMeta",
        __Marshaller_sdmxdl_grpc_FlowRequestDto,
        __Marshaller_sdmxdl_format_protobuf_MetaSetDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.KeyRequestDto, global::Sdmxdl.Format.Protobuf.DataSetDto> __Method_GetData = new grpc::Method<global::Sdmxdl.Grpc.KeyRequestDto, global::Sdmxdl.Format.Protobuf.DataSetDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetData",
        __Marshaller_sdmxdl_grpc_KeyRequestDto,
        __Marshaller_sdmxdl_format_protobuf_DataSetDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.KeyRequestDto, global::Sdmxdl.Format.Protobuf.SeriesDto> __Method_GetDataStream = new grpc::Method<global::Sdmxdl.Grpc.KeyRequestDto, global::Sdmxdl.Format.Protobuf.SeriesDto>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetDataStream",
        __Marshaller_sdmxdl_grpc_KeyRequestDto,
        __Marshaller_sdmxdl_format_protobuf_SeriesDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sdmxdl.Grpc.KeyDimensionRequestDto, global::Sdmxdl.Grpc.DimensionCodesDto> __Method_GetAvailability = new grpc::Method<global::Sdmxdl.Grpc.KeyDimensionRequestDto, global::Sdmxdl.Grpc.DimensionCodesDto>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAvailability",
        __Marshaller_sdmxdl_grpc_KeyDimensionRequestDto,
        __Marshaller_sdmxdl_grpc_DimensionCodesDto);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sdmxdl.Grpc.SdmxdlGrpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for SdmxWebManager</summary>
    public partial class SdmxWebManagerClient : grpc::ClientBase<SdmxWebManagerClient>
    {
      /// <summary>Creates a new client for SdmxWebManager</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SdmxWebManagerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SdmxWebManager that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SdmxWebManagerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SdmxWebManagerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SdmxWebManagerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sdmxdl.Format.Protobuf.AboutDto GetAbout(global::Sdmxdl.Grpc.EmptyDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAbout(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sdmxdl.Format.Protobuf.AboutDto GetAbout(global::Sdmxdl.Grpc.EmptyDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAbout, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sdmxdl.Format.Protobuf.AboutDto> GetAboutAsync(global::Sdmxdl.Grpc.EmptyDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAboutAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sdmxdl.Format.Protobuf.AboutDto> GetAboutAsync(global::Sdmxdl.Grpc.EmptyDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAbout, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Format.Protobuf.Web.WebSourceDto> GetSources(global::Sdmxdl.Grpc.EmptyDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSources(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Format.Protobuf.Web.WebSourceDto> GetSources(global::Sdmxdl.Grpc.EmptyDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetSources, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto GetMonitorReport(global::Sdmxdl.Grpc.SourceRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMonitorReport(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto GetMonitorReport(global::Sdmxdl.Grpc.SourceRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMonitorReport, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto> GetMonitorReportAsync(global::Sdmxdl.Grpc.SourceRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMonitorReportAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto> GetMonitorReportAsync(global::Sdmxdl.Grpc.SourceRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMonitorReport, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Format.Protobuf.DatabaseDto> GetDatabases(global::Sdmxdl.Grpc.SourceRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDatabases(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Format.Protobuf.DatabaseDto> GetDatabases(global::Sdmxdl.Grpc.SourceRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetDatabases, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Format.Protobuf.FlowDto> GetFlows(global::Sdmxdl.Grpc.DatabaseRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFlows(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Format.Protobuf.FlowDto> GetFlows(global::Sdmxdl.Grpc.DatabaseRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetFlows, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sdmxdl.Format.Protobuf.MetaSetDto GetMeta(global::Sdmxdl.Grpc.FlowRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMeta(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sdmxdl.Format.Protobuf.MetaSetDto GetMeta(global::Sdmxdl.Grpc.FlowRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMeta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sdmxdl.Format.Protobuf.MetaSetDto> GetMetaAsync(global::Sdmxdl.Grpc.FlowRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMetaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sdmxdl.Format.Protobuf.MetaSetDto> GetMetaAsync(global::Sdmxdl.Grpc.FlowRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMeta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sdmxdl.Format.Protobuf.DataSetDto GetData(global::Sdmxdl.Grpc.KeyRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sdmxdl.Format.Protobuf.DataSetDto GetData(global::Sdmxdl.Grpc.KeyRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sdmxdl.Format.Protobuf.DataSetDto> GetDataAsync(global::Sdmxdl.Grpc.KeyRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sdmxdl.Format.Protobuf.DataSetDto> GetDataAsync(global::Sdmxdl.Grpc.KeyRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Format.Protobuf.SeriesDto> GetDataStream(global::Sdmxdl.Grpc.KeyRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDataStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Format.Protobuf.SeriesDto> GetDataStream(global::Sdmxdl.Grpc.KeyRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetDataStream, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Grpc.DimensionCodesDto> GetAvailability(global::Sdmxdl.Grpc.KeyDimensionRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAvailability(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Sdmxdl.Grpc.DimensionCodesDto> GetAvailability(global::Sdmxdl.Grpc.KeyDimensionRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAvailability, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SdmxWebManagerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SdmxWebManagerClient(configuration);
      }
    }

  }
}
#endregion
