// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sdmxdl_monitor.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sdmxdl.Format.Protobuf.Web {

  /// <summary>Holder for reflection information generated from sdmxdl_monitor.proto</summary>
  public static partial class SdmxdlMonitorReflection {

    #region Descriptor
    /// <summary>File descriptor for sdmxdl_monitor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SdmxdlMonitorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRzZG14ZGxfbW9uaXRvci5wcm90bxIac2RteGRsLmZvcm1hdC5wcm90b2J1",
            "Zi53ZWIixAEKDU1vbml0b3JSZXBvcnQSDgoGc291cmNlGAEgASgJEjkKBnN0",
            "YXR1cxgCIAEoDjIpLnNkbXhkbC5mb3JtYXQucHJvdG9idWYud2ViLk1vbml0",
            "b3JTdGF0dXMSGQoMdXB0aW1lX3JhdGlvGAMgASgBSACIAQESIgoVYXZlcmFn",
            "ZV9yZXNwb25zZV90aW1lGAQgASgDSAGIAQFCDwoNX3VwdGltZV9yYXRpb0IY",
            "ChZfYXZlcmFnZV9yZXNwb25zZV90aW1lIpABCg5Nb25pdG9yUmVwb3J0cxIS",
            "Cgp1cmlfc2NoZW1lGAEgASgJEjoKB3JlcG9ydHMYAiADKAsyKS5zZG14ZGwu",
            "Zm9ybWF0LnByb3RvYnVmLndlYi5Nb25pdG9yUmVwb3J0EhUKDWNyZWF0aW9u",
            "X3RpbWUYAyABKAkSFwoPZXhwaXJhdGlvbl90aW1lGAQgASgJKi4KDU1vbml0",
            "b3JTdGF0dXMSCwoHVU5LTk9XThAAEgYKAlVQEAESCAoERE9XThACQgJQAWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sdmxdl.Format.Protobuf.Web.MonitorStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.MonitorReport), global::Sdmxdl.Format.Protobuf.Web.MonitorReport.Parser, new[]{ "Source", "Status", "UptimeRatio", "AverageResponseTime" }, new[]{ "UptimeRatio", "AverageResponseTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.MonitorReports), global::Sdmxdl.Format.Protobuf.Web.MonitorReports.Parser, new[]{ "UriScheme", "Reports", "CreationTime", "ExpirationTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MonitorStatus {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("UP")] Up = 1,
    [pbr::OriginalName("DOWN")] Down = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MonitorReport : pb::IMessage<MonitorReport>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonitorReport> _parser = new pb::MessageParser<MonitorReport>(() => new MonitorReport());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonitorReport> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SdmxdlMonitorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReport() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReport(MonitorReport other) : this() {
      _hasBits0 = other._hasBits0;
      source_ = other.source_;
      status_ = other.status_;
      uptimeRatio_ = other.uptimeRatio_;
      averageResponseTime_ = other.averageResponseTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReport Clone() {
      return new MonitorReport(this);
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 1;
    private string source_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Source {
      get { return source_; }
      set {
        source_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Sdmxdl.Format.Protobuf.Web.MonitorStatus status_ = global::Sdmxdl.Format.Protobuf.Web.MonitorStatus.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Sdmxdl.Format.Protobuf.Web.MonitorStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "uptime_ratio" field.</summary>
    public const int UptimeRatioFieldNumber = 3;
    private readonly static double UptimeRatioDefaultValue = 0D;

    private double uptimeRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double UptimeRatio {
      get { if ((_hasBits0 & 1) != 0) { return uptimeRatio_; } else { return UptimeRatioDefaultValue; } }
      set {
        _hasBits0 |= 1;
        uptimeRatio_ = value;
      }
    }
    /// <summary>Gets whether the "uptime_ratio" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUptimeRatio {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "uptime_ratio" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUptimeRatio() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "average_response_time" field.</summary>
    public const int AverageResponseTimeFieldNumber = 4;
    private readonly static long AverageResponseTimeDefaultValue = 0L;

    private long averageResponseTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AverageResponseTime {
      get { if ((_hasBits0 & 2) != 0) { return averageResponseTime_; } else { return AverageResponseTimeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        averageResponseTime_ = value;
      }
    }
    /// <summary>Gets whether the "average_response_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAverageResponseTime {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "average_response_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAverageResponseTime() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonitorReport);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonitorReport other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Source != other.Source) return false;
      if (Status != other.Status) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UptimeRatio, other.UptimeRatio)) return false;
      if (AverageResponseTime != other.AverageResponseTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Source.Length != 0) hash ^= Source.GetHashCode();
      if (Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatus.Unknown) hash ^= Status.GetHashCode();
      if (HasUptimeRatio) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UptimeRatio);
      if (HasAverageResponseTime) hash ^= AverageResponseTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Source.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Source);
      }
      if (Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatus.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (HasUptimeRatio) {
        output.WriteRawTag(25);
        output.WriteDouble(UptimeRatio);
      }
      if (HasAverageResponseTime) {
        output.WriteRawTag(32);
        output.WriteInt64(AverageResponseTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Source.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Source);
      }
      if (Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatus.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (HasUptimeRatio) {
        output.WriteRawTag(25);
        output.WriteDouble(UptimeRatio);
      }
      if (HasAverageResponseTime) {
        output.WriteRawTag(32);
        output.WriteInt64(AverageResponseTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Source.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Source);
      }
      if (Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatus.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (HasUptimeRatio) {
        size += 1 + 8;
      }
      if (HasAverageResponseTime) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AverageResponseTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonitorReport other) {
      if (other == null) {
        return;
      }
      if (other.Source.Length != 0) {
        Source = other.Source;
      }
      if (other.Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatus.Unknown) {
        Status = other.Status;
      }
      if (other.HasUptimeRatio) {
        UptimeRatio = other.UptimeRatio;
      }
      if (other.HasAverageResponseTime) {
        AverageResponseTime = other.AverageResponseTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Source = input.ReadString();
            break;
          }
          case 16: {
            Status = (global::Sdmxdl.Format.Protobuf.Web.MonitorStatus) input.ReadEnum();
            break;
          }
          case 25: {
            UptimeRatio = input.ReadDouble();
            break;
          }
          case 32: {
            AverageResponseTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Source = input.ReadString();
            break;
          }
          case 16: {
            Status = (global::Sdmxdl.Format.Protobuf.Web.MonitorStatus) input.ReadEnum();
            break;
          }
          case 25: {
            UptimeRatio = input.ReadDouble();
            break;
          }
          case 32: {
            AverageResponseTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MonitorReports : pb::IMessage<MonitorReports>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonitorReports> _parser = new pb::MessageParser<MonitorReports>(() => new MonitorReports());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonitorReports> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SdmxdlMonitorReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReports() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReports(MonitorReports other) : this() {
      uriScheme_ = other.uriScheme_;
      reports_ = other.reports_.Clone();
      creationTime_ = other.creationTime_;
      expirationTime_ = other.expirationTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReports Clone() {
      return new MonitorReports(this);
    }

    /// <summary>Field number for the "uri_scheme" field.</summary>
    public const int UriSchemeFieldNumber = 1;
    private string uriScheme_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UriScheme {
      get { return uriScheme_; }
      set {
        uriScheme_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reports" field.</summary>
    public const int ReportsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Sdmxdl.Format.Protobuf.Web.MonitorReport> _repeated_reports_codec
        = pb::FieldCodec.ForMessage(18, global::Sdmxdl.Format.Protobuf.Web.MonitorReport.Parser);
    private readonly pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.MonitorReport> reports_ = new pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.MonitorReport>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.MonitorReport> Reports {
      get { return reports_; }
    }

    /// <summary>Field number for the "creation_time" field.</summary>
    public const int CreationTimeFieldNumber = 3;
    private string creationTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CreationTime {
      get { return creationTime_; }
      set {
        creationTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expiration_time" field.</summary>
    public const int ExpirationTimeFieldNumber = 4;
    private string expirationTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExpirationTime {
      get { return expirationTime_; }
      set {
        expirationTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonitorReports);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonitorReports other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UriScheme != other.UriScheme) return false;
      if(!reports_.Equals(other.reports_)) return false;
      if (CreationTime != other.CreationTime) return false;
      if (ExpirationTime != other.ExpirationTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UriScheme.Length != 0) hash ^= UriScheme.GetHashCode();
      hash ^= reports_.GetHashCode();
      if (CreationTime.Length != 0) hash ^= CreationTime.GetHashCode();
      if (ExpirationTime.Length != 0) hash ^= ExpirationTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UriScheme.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UriScheme);
      }
      reports_.WriteTo(output, _repeated_reports_codec);
      if (CreationTime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CreationTime);
      }
      if (ExpirationTime.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExpirationTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UriScheme.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UriScheme);
      }
      reports_.WriteTo(ref output, _repeated_reports_codec);
      if (CreationTime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CreationTime);
      }
      if (ExpirationTime.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExpirationTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UriScheme.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UriScheme);
      }
      size += reports_.CalculateSize(_repeated_reports_codec);
      if (CreationTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreationTime);
      }
      if (ExpirationTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExpirationTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonitorReports other) {
      if (other == null) {
        return;
      }
      if (other.UriScheme.Length != 0) {
        UriScheme = other.UriScheme;
      }
      reports_.Add(other.reports_);
      if (other.CreationTime.Length != 0) {
        CreationTime = other.CreationTime;
      }
      if (other.ExpirationTime.Length != 0) {
        ExpirationTime = other.ExpirationTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UriScheme = input.ReadString();
            break;
          }
          case 18: {
            reports_.AddEntriesFrom(input, _repeated_reports_codec);
            break;
          }
          case 26: {
            CreationTime = input.ReadString();
            break;
          }
          case 34: {
            ExpirationTime = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UriScheme = input.ReadString();
            break;
          }
          case 18: {
            reports_.AddEntriesFrom(ref input, _repeated_reports_codec);
            break;
          }
          case 26: {
            CreationTime = input.ReadString();
            break;
          }
          case 34: {
            ExpirationTime = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
