// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sdmxdl_source.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sdmxdl.Format.Protobuf.Web {

  /// <summary>Holder for reflection information generated from sdmxdl_source.proto</summary>
  public static partial class SdmxdlSourceReflection {

    #region Descriptor
    /// <summary>File descriptor for sdmxdl_source.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SdmxdlSourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzZG14ZGxfc291cmNlLnByb3RvEhpzZG14ZGwuZm9ybWF0LnByb3RvYnVm",
            "LndlYiL/AwoNU2RteFdlYlNvdXJjZRIKCgJpZBgBIAEoCRJDCgVuYW1lcxgC",
            "IAMoCzI0LnNkbXhkbC5mb3JtYXQucHJvdG9idWYud2ViLlNkbXhXZWJTb3Vy",
            "Y2UuTmFtZXNFbnRyeRIOCgZkcml2ZXIYAyABKAkSEAoIZW5kcG9pbnQYBCAB",
            "KAkSTQoKcHJvcGVydGllcxgFIAMoCzI5LnNkbXhkbC5mb3JtYXQucHJvdG9i",
            "dWYud2ViLlNkbXhXZWJTb3VyY2UuUHJvcGVydGllc0VudHJ5Eg8KB2FsaWFz",
            "ZXMYBiADKAkSFAoHd2Vic2l0ZRgHIAEoCUgAiAEBEhQKB21vbml0b3IYCCAB",
            "KAlIAYgBARIcCg9tb25pdG9yX3dlYnNpdGUYCSABKAlIAogBARJECg9jb25m",
            "aWRlbnRpYWxpdHkYCiABKA4yKy5zZG14ZGwuZm9ybWF0LnByb3RvYnVmLndl",
            "Yi5Db25maWRlbnRpYWxpdHkaLAoKTmFtZXNFbnRyeRILCgNrZXkYASABKAkS",
            "DQoFdmFsdWUYAiABKAk6AjgBGjEKD1Byb3BlcnRpZXNFbnRyeRILCgNrZXkY",
            "ASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQgoKCF93ZWJzaXRlQgoKCF9tb25p",
            "dG9yQhIKEF9tb25pdG9yX3dlYnNpdGUiTAoKV2ViU291cmNlcxI+Cgt3ZWJf",
            "c291cmNlcxgBIAMoCzIpLnNkbXhkbC5mb3JtYXQucHJvdG9idWYud2ViLlNk",
            "bXhXZWJTb3VyY2UqXQoPQ29uZmlkZW50aWFsaXR5EgoKBlBVQkxJQxAAEhAK",
            "DFVOUkVTVFJJQ1RFRBABEg4KClJFU1RSSUNURUQQAhIQCgxDT05GSURFTlRJ",
            "QUwQAxIKCgZTRUNSRVQQBEICUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sdmxdl.Format.Protobuf.Web.Confidentiality), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource), global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource.Parser, new[]{ "Id", "Names", "Driver", "Endpoint", "Properties", "Aliases", "Website", "Monitor", "MonitorWebsite", "Confidentiality" }, new[]{ "Website", "Monitor", "MonitorWebsite" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.WebSources), global::Sdmxdl.Format.Protobuf.Web.WebSources.Parser, new[]{ "WebSources_" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Confidentiality {
    [pbr::OriginalName("PUBLIC")] Public = 0,
    [pbr::OriginalName("UNRESTRICTED")] Unrestricted = 1,
    [pbr::OriginalName("RESTRICTED")] Restricted = 2,
    [pbr::OriginalName("CONFIDENTIAL")] Confidential = 3,
    [pbr::OriginalName("SECRET")] Secret = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SdmxWebSource : pb::IMessage<SdmxWebSource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SdmxWebSource> _parser = new pb::MessageParser<SdmxWebSource>(() => new SdmxWebSource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SdmxWebSource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SdmxdlSourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SdmxWebSource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SdmxWebSource(SdmxWebSource other) : this() {
      id_ = other.id_;
      names_ = other.names_.Clone();
      driver_ = other.driver_;
      endpoint_ = other.endpoint_;
      properties_ = other.properties_.Clone();
      aliases_ = other.aliases_.Clone();
      website_ = other.website_;
      monitor_ = other.monitor_;
      monitorWebsite_ = other.monitorWebsite_;
      confidentiality_ = other.confidentiality_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SdmxWebSource Clone() {
      return new SdmxWebSource(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "names" field.</summary>
    public const int NamesFieldNumber = 2;
    private static readonly pbc::MapField<string, string>.Codec _map_names_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 18);
    private readonly pbc::MapField<string, string> names_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Names {
      get { return names_; }
    }

    /// <summary>Field number for the "driver" field.</summary>
    public const int DriverFieldNumber = 3;
    private string driver_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Driver {
      get { return driver_; }
      set {
        driver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endpoint" field.</summary>
    public const int EndpointFieldNumber = 4;
    private string endpoint_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Endpoint {
      get { return endpoint_; }
      set {
        endpoint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 5;
    private static readonly pbc::MapField<string, string>.Codec _map_properties_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 42);
    private readonly pbc::MapField<string, string> properties_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Properties {
      get { return properties_; }
    }

    /// <summary>Field number for the "aliases" field.</summary>
    public const int AliasesFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_aliases_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> aliases_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Aliases {
      get { return aliases_; }
    }

    /// <summary>Field number for the "website" field.</summary>
    public const int WebsiteFieldNumber = 7;
    private readonly static string WebsiteDefaultValue = "";

    private string website_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Website {
      get { return website_ ?? WebsiteDefaultValue; }
      set {
        website_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "website" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWebsite {
      get { return website_ != null; }
    }
    /// <summary>Clears the value of the "website" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWebsite() {
      website_ = null;
    }

    /// <summary>Field number for the "monitor" field.</summary>
    public const int MonitorFieldNumber = 8;
    private readonly static string MonitorDefaultValue = "";

    private string monitor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Monitor {
      get { return monitor_ ?? MonitorDefaultValue; }
      set {
        monitor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "monitor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMonitor {
      get { return monitor_ != null; }
    }
    /// <summary>Clears the value of the "monitor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMonitor() {
      monitor_ = null;
    }

    /// <summary>Field number for the "monitor_website" field.</summary>
    public const int MonitorWebsiteFieldNumber = 9;
    private readonly static string MonitorWebsiteDefaultValue = "";

    private string monitorWebsite_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MonitorWebsite {
      get { return monitorWebsite_ ?? MonitorWebsiteDefaultValue; }
      set {
        monitorWebsite_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "monitor_website" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMonitorWebsite {
      get { return monitorWebsite_ != null; }
    }
    /// <summary>Clears the value of the "monitor_website" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMonitorWebsite() {
      monitorWebsite_ = null;
    }

    /// <summary>Field number for the "confidentiality" field.</summary>
    public const int ConfidentialityFieldNumber = 10;
    private global::Sdmxdl.Format.Protobuf.Web.Confidentiality confidentiality_ = global::Sdmxdl.Format.Protobuf.Web.Confidentiality.Public;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Sdmxdl.Format.Protobuf.Web.Confidentiality Confidentiality {
      get { return confidentiality_; }
      set {
        confidentiality_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SdmxWebSource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SdmxWebSource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!Names.Equals(other.Names)) return false;
      if (Driver != other.Driver) return false;
      if (Endpoint != other.Endpoint) return false;
      if (!Properties.Equals(other.Properties)) return false;
      if(!aliases_.Equals(other.aliases_)) return false;
      if (Website != other.Website) return false;
      if (Monitor != other.Monitor) return false;
      if (MonitorWebsite != other.MonitorWebsite) return false;
      if (Confidentiality != other.Confidentiality) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= Names.GetHashCode();
      if (Driver.Length != 0) hash ^= Driver.GetHashCode();
      if (Endpoint.Length != 0) hash ^= Endpoint.GetHashCode();
      hash ^= Properties.GetHashCode();
      hash ^= aliases_.GetHashCode();
      if (HasWebsite) hash ^= Website.GetHashCode();
      if (HasMonitor) hash ^= Monitor.GetHashCode();
      if (HasMonitorWebsite) hash ^= MonitorWebsite.GetHashCode();
      if (Confidentiality != global::Sdmxdl.Format.Protobuf.Web.Confidentiality.Public) hash ^= Confidentiality.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      names_.WriteTo(output, _map_names_codec);
      if (Driver.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Driver);
      }
      if (Endpoint.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Endpoint);
      }
      properties_.WriteTo(output, _map_properties_codec);
      aliases_.WriteTo(output, _repeated_aliases_codec);
      if (HasWebsite) {
        output.WriteRawTag(58);
        output.WriteString(Website);
      }
      if (HasMonitor) {
        output.WriteRawTag(66);
        output.WriteString(Monitor);
      }
      if (HasMonitorWebsite) {
        output.WriteRawTag(74);
        output.WriteString(MonitorWebsite);
      }
      if (Confidentiality != global::Sdmxdl.Format.Protobuf.Web.Confidentiality.Public) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Confidentiality);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      names_.WriteTo(ref output, _map_names_codec);
      if (Driver.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Driver);
      }
      if (Endpoint.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Endpoint);
      }
      properties_.WriteTo(ref output, _map_properties_codec);
      aliases_.WriteTo(ref output, _repeated_aliases_codec);
      if (HasWebsite) {
        output.WriteRawTag(58);
        output.WriteString(Website);
      }
      if (HasMonitor) {
        output.WriteRawTag(66);
        output.WriteString(Monitor);
      }
      if (HasMonitorWebsite) {
        output.WriteRawTag(74);
        output.WriteString(MonitorWebsite);
      }
      if (Confidentiality != global::Sdmxdl.Format.Protobuf.Web.Confidentiality.Public) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Confidentiality);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      size += names_.CalculateSize(_map_names_codec);
      if (Driver.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Driver);
      }
      if (Endpoint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Endpoint);
      }
      size += properties_.CalculateSize(_map_properties_codec);
      size += aliases_.CalculateSize(_repeated_aliases_codec);
      if (HasWebsite) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Website);
      }
      if (HasMonitor) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Monitor);
      }
      if (HasMonitorWebsite) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MonitorWebsite);
      }
      if (Confidentiality != global::Sdmxdl.Format.Protobuf.Web.Confidentiality.Public) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Confidentiality);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SdmxWebSource other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      names_.MergeFrom(other.names_);
      if (other.Driver.Length != 0) {
        Driver = other.Driver;
      }
      if (other.Endpoint.Length != 0) {
        Endpoint = other.Endpoint;
      }
      properties_.MergeFrom(other.properties_);
      aliases_.Add(other.aliases_);
      if (other.HasWebsite) {
        Website = other.Website;
      }
      if (other.HasMonitor) {
        Monitor = other.Monitor;
      }
      if (other.HasMonitorWebsite) {
        MonitorWebsite = other.MonitorWebsite;
      }
      if (other.Confidentiality != global::Sdmxdl.Format.Protobuf.Web.Confidentiality.Public) {
        Confidentiality = other.Confidentiality;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            names_.AddEntriesFrom(input, _map_names_codec);
            break;
          }
          case 26: {
            Driver = input.ReadString();
            break;
          }
          case 34: {
            Endpoint = input.ReadString();
            break;
          }
          case 42: {
            properties_.AddEntriesFrom(input, _map_properties_codec);
            break;
          }
          case 50: {
            aliases_.AddEntriesFrom(input, _repeated_aliases_codec);
            break;
          }
          case 58: {
            Website = input.ReadString();
            break;
          }
          case 66: {
            Monitor = input.ReadString();
            break;
          }
          case 74: {
            MonitorWebsite = input.ReadString();
            break;
          }
          case 80: {
            Confidentiality = (global::Sdmxdl.Format.Protobuf.Web.Confidentiality) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            names_.AddEntriesFrom(ref input, _map_names_codec);
            break;
          }
          case 26: {
            Driver = input.ReadString();
            break;
          }
          case 34: {
            Endpoint = input.ReadString();
            break;
          }
          case 42: {
            properties_.AddEntriesFrom(ref input, _map_properties_codec);
            break;
          }
          case 50: {
            aliases_.AddEntriesFrom(ref input, _repeated_aliases_codec);
            break;
          }
          case 58: {
            Website = input.ReadString();
            break;
          }
          case 66: {
            Monitor = input.ReadString();
            break;
          }
          case 74: {
            MonitorWebsite = input.ReadString();
            break;
          }
          case 80: {
            Confidentiality = (global::Sdmxdl.Format.Protobuf.Web.Confidentiality) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WebSources : pb::IMessage<WebSources>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WebSources> _parser = new pb::MessageParser<WebSources>(() => new WebSources());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WebSources> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SdmxdlSourceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSources() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSources(WebSources other) : this() {
      webSources_ = other.webSources_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSources Clone() {
      return new WebSources(this);
    }

    /// <summary>Field number for the "web_sources" field.</summary>
    public const int WebSources_FieldNumber = 1;
    private static readonly pb::FieldCodec<global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource> _repeated_webSources_codec
        = pb::FieldCodec.ForMessage(10, global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource.Parser);
    private readonly pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource> webSources_ = new pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource> WebSources_ {
      get { return webSources_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WebSources);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WebSources other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!webSources_.Equals(other.webSources_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= webSources_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      webSources_.WriteTo(output, _repeated_webSources_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      webSources_.WriteTo(ref output, _repeated_webSources_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += webSources_.CalculateSize(_repeated_webSources_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WebSources other) {
      if (other == null) {
        return;
      }
      webSources_.Add(other.webSources_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            webSources_.AddEntriesFrom(input, _repeated_webSources_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            webSources_.AddEntriesFrom(ref input, _repeated_webSources_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
