// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sdmxdl_web.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sdmxdl.Format.Protobuf.Web {

  /// <summary>Holder for reflection information generated from sdmxdl_web.proto</summary>
  public static partial class SdmxdlWebReflection {

    #region Descriptor
    /// <summary>File descriptor for sdmxdl_web.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SdmxdlWebReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBzZG14ZGxfd2ViLnByb3RvEhpzZG14ZGwuZm9ybWF0LnByb3RvYnVmLndl",
            "YhoQc2RteGRsX2FwaS5wcm90byL7AwoMV2ViU291cmNlRHRvEgoKAmlkGAEg",
            "ASgJEkIKBW5hbWVzGAIgAygLMjMuc2RteGRsLmZvcm1hdC5wcm90b2J1Zi53",
            "ZWIuV2ViU291cmNlRHRvLk5hbWVzRW50cnkSDgoGZHJpdmVyGAMgASgJEhAK",
            "CGVuZHBvaW50GAQgASgJEkwKCnByb3BlcnRpZXMYBSADKAsyOC5zZG14ZGwu",
            "Zm9ybWF0LnByb3RvYnVmLndlYi5XZWJTb3VyY2VEdG8uUHJvcGVydGllc0Vu",
            "dHJ5Eg8KB2FsaWFzZXMYBiADKAkSFAoHd2Vic2l0ZRgHIAEoCUgAiAEBEhQK",
            "B21vbml0b3IYCCABKAlIAYgBARIcCg9tb25pdG9yX3dlYnNpdGUYCSABKAlI",
            "AogBARJDCg9jb25maWRlbnRpYWxpdHkYCiABKA4yKi5zZG14ZGwuZm9ybWF0",
            "LnByb3RvYnVmLkNvbmZpZGVudGlhbGl0eUR0bxosCgpOYW1lc0VudHJ5EgsK",
            "A2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaMQoPUHJvcGVydGllc0Vu",
            "dHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCCgoIX3dlYnNp",
            "dGVCCgoIX21vbml0b3JCEgoQX21vbml0b3Jfd2Vic2l0ZSJOCg1XZWJTb3Vy",
            "Y2VzRHRvEj0KC3dlYl9zb3VyY2VzGAEgAygLMiguc2RteGRsLmZvcm1hdC5w",
            "cm90b2J1Zi53ZWIuV2ViU291cmNlRHRvIsoBChBNb25pdG9yUmVwb3J0RHRv",
            "Eg4KBnNvdXJjZRgBIAEoCRI8CgZzdGF0dXMYAiABKA4yLC5zZG14ZGwuZm9y",
            "bWF0LnByb3RvYnVmLndlYi5Nb25pdG9yU3RhdHVzRHRvEhkKDHVwdGltZV9y",
            "YXRpbxgDIAEoAUgAiAEBEiIKFWF2ZXJhZ2VfcmVzcG9uc2VfdGltZRgEIAEo",
            "A0gBiAEBQg8KDV91cHRpbWVfcmF0aW9CGAoWX2F2ZXJhZ2VfcmVzcG9uc2Vf",
            "dGltZSKWAQoRTW9uaXRvclJlcG9ydHNEdG8SEgoKdXJpX3NjaGVtZRgBIAEo",
            "CRI9CgdyZXBvcnRzGAIgAygLMiwuc2RteGRsLmZvcm1hdC5wcm90b2J1Zi53",
            "ZWIuTW9uaXRvclJlcG9ydER0bxIVCg1jcmVhdGlvbl90aW1lGAMgASgJEhcK",
            "D2V4cGlyYXRpb25fdGltZRgEIAEoCSoxChBNb25pdG9yU3RhdHVzRHRvEgsK",
            "B1VOS05PV04QABIGCgJVUBABEggKBERPV04QAkICUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Sdmxdl.Format.Protobuf.SdmxdlApiReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.WebSourceDto), global::Sdmxdl.Format.Protobuf.Web.WebSourceDto.Parser, new[]{ "Id", "Names", "Driver", "Endpoint", "Properties", "Aliases", "Website", "Monitor", "MonitorWebsite", "Confidentiality" }, new[]{ "Website", "Monitor", "MonitorWebsite" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.WebSourcesDto), global::Sdmxdl.Format.Protobuf.Web.WebSourcesDto.Parser, new[]{ "WebSources" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto), global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto.Parser, new[]{ "Source", "Status", "UptimeRatio", "AverageResponseTime" }, new[]{ "UptimeRatio", "AverageResponseTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.MonitorReportsDto), global::Sdmxdl.Format.Protobuf.Web.MonitorReportsDto.Parser, new[]{ "UriScheme", "Reports", "CreationTime", "ExpirationTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MonitorStatusDto {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("UP")] Up = 1,
    [pbr::OriginalName("DOWN")] Down = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WebSourceDto : pb::IMessage<WebSourceDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WebSourceDto> _parser = new pb::MessageParser<WebSourceDto>(() => new WebSourceDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WebSourceDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SdmxdlWebReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSourceDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSourceDto(WebSourceDto other) : this() {
      id_ = other.id_;
      names_ = other.names_.Clone();
      driver_ = other.driver_;
      endpoint_ = other.endpoint_;
      properties_ = other.properties_.Clone();
      aliases_ = other.aliases_.Clone();
      website_ = other.website_;
      monitor_ = other.monitor_;
      monitorWebsite_ = other.monitorWebsite_;
      confidentiality_ = other.confidentiality_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSourceDto Clone() {
      return new WebSourceDto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "names" field.</summary>
    public const int NamesFieldNumber = 2;
    private static readonly pbc::MapField<string, string>.Codec _map_names_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 18);
    private readonly pbc::MapField<string, string> names_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Names {
      get { return names_; }
    }

    /// <summary>Field number for the "driver" field.</summary>
    public const int DriverFieldNumber = 3;
    private string driver_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Driver {
      get { return driver_; }
      set {
        driver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endpoint" field.</summary>
    public const int EndpointFieldNumber = 4;
    private string endpoint_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Endpoint {
      get { return endpoint_; }
      set {
        endpoint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 5;
    private static readonly pbc::MapField<string, string>.Codec _map_properties_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 42);
    private readonly pbc::MapField<string, string> properties_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Properties {
      get { return properties_; }
    }

    /// <summary>Field number for the "aliases" field.</summary>
    public const int AliasesFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_aliases_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> aliases_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Aliases {
      get { return aliases_; }
    }

    /// <summary>Field number for the "website" field.</summary>
    public const int WebsiteFieldNumber = 7;
    private readonly static string WebsiteDefaultValue = "";

    private string website_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Website {
      get { return website_ ?? WebsiteDefaultValue; }
      set {
        website_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "website" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWebsite {
      get { return website_ != null; }
    }
    /// <summary>Clears the value of the "website" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWebsite() {
      website_ = null;
    }

    /// <summary>Field number for the "monitor" field.</summary>
    public const int MonitorFieldNumber = 8;
    private readonly static string MonitorDefaultValue = "";

    private string monitor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Monitor {
      get { return monitor_ ?? MonitorDefaultValue; }
      set {
        monitor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "monitor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMonitor {
      get { return monitor_ != null; }
    }
    /// <summary>Clears the value of the "monitor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMonitor() {
      monitor_ = null;
    }

    /// <summary>Field number for the "monitor_website" field.</summary>
    public const int MonitorWebsiteFieldNumber = 9;
    private readonly static string MonitorWebsiteDefaultValue = "";

    private string monitorWebsite_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MonitorWebsite {
      get { return monitorWebsite_ ?? MonitorWebsiteDefaultValue; }
      set {
        monitorWebsite_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "monitor_website" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMonitorWebsite {
      get { return monitorWebsite_ != null; }
    }
    /// <summary>Clears the value of the "monitor_website" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMonitorWebsite() {
      monitorWebsite_ = null;
    }

    /// <summary>Field number for the "confidentiality" field.</summary>
    public const int ConfidentialityFieldNumber = 10;
    private global::Sdmxdl.Format.Protobuf.ConfidentialityDto confidentiality_ = global::Sdmxdl.Format.Protobuf.ConfidentialityDto.Public;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Sdmxdl.Format.Protobuf.ConfidentialityDto Confidentiality {
      get { return confidentiality_; }
      set {
        confidentiality_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WebSourceDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WebSourceDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!Names.Equals(other.Names)) return false;
      if (Driver != other.Driver) return false;
      if (Endpoint != other.Endpoint) return false;
      if (!Properties.Equals(other.Properties)) return false;
      if(!aliases_.Equals(other.aliases_)) return false;
      if (Website != other.Website) return false;
      if (Monitor != other.Monitor) return false;
      if (MonitorWebsite != other.MonitorWebsite) return false;
      if (Confidentiality != other.Confidentiality) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= Names.GetHashCode();
      if (Driver.Length != 0) hash ^= Driver.GetHashCode();
      if (Endpoint.Length != 0) hash ^= Endpoint.GetHashCode();
      hash ^= Properties.GetHashCode();
      hash ^= aliases_.GetHashCode();
      if (HasWebsite) hash ^= Website.GetHashCode();
      if (HasMonitor) hash ^= Monitor.GetHashCode();
      if (HasMonitorWebsite) hash ^= MonitorWebsite.GetHashCode();
      if (Confidentiality != global::Sdmxdl.Format.Protobuf.ConfidentialityDto.Public) hash ^= Confidentiality.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      names_.WriteTo(output, _map_names_codec);
      if (Driver.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Driver);
      }
      if (Endpoint.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Endpoint);
      }
      properties_.WriteTo(output, _map_properties_codec);
      aliases_.WriteTo(output, _repeated_aliases_codec);
      if (HasWebsite) {
        output.WriteRawTag(58);
        output.WriteString(Website);
      }
      if (HasMonitor) {
        output.WriteRawTag(66);
        output.WriteString(Monitor);
      }
      if (HasMonitorWebsite) {
        output.WriteRawTag(74);
        output.WriteString(MonitorWebsite);
      }
      if (Confidentiality != global::Sdmxdl.Format.Protobuf.ConfidentialityDto.Public) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Confidentiality);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      names_.WriteTo(ref output, _map_names_codec);
      if (Driver.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Driver);
      }
      if (Endpoint.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Endpoint);
      }
      properties_.WriteTo(ref output, _map_properties_codec);
      aliases_.WriteTo(ref output, _repeated_aliases_codec);
      if (HasWebsite) {
        output.WriteRawTag(58);
        output.WriteString(Website);
      }
      if (HasMonitor) {
        output.WriteRawTag(66);
        output.WriteString(Monitor);
      }
      if (HasMonitorWebsite) {
        output.WriteRawTag(74);
        output.WriteString(MonitorWebsite);
      }
      if (Confidentiality != global::Sdmxdl.Format.Protobuf.ConfidentialityDto.Public) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Confidentiality);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      size += names_.CalculateSize(_map_names_codec);
      if (Driver.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Driver);
      }
      if (Endpoint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Endpoint);
      }
      size += properties_.CalculateSize(_map_properties_codec);
      size += aliases_.CalculateSize(_repeated_aliases_codec);
      if (HasWebsite) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Website);
      }
      if (HasMonitor) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Monitor);
      }
      if (HasMonitorWebsite) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MonitorWebsite);
      }
      if (Confidentiality != global::Sdmxdl.Format.Protobuf.ConfidentialityDto.Public) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Confidentiality);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WebSourceDto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      names_.MergeFrom(other.names_);
      if (other.Driver.Length != 0) {
        Driver = other.Driver;
      }
      if (other.Endpoint.Length != 0) {
        Endpoint = other.Endpoint;
      }
      properties_.MergeFrom(other.properties_);
      aliases_.Add(other.aliases_);
      if (other.HasWebsite) {
        Website = other.Website;
      }
      if (other.HasMonitor) {
        Monitor = other.Monitor;
      }
      if (other.HasMonitorWebsite) {
        MonitorWebsite = other.MonitorWebsite;
      }
      if (other.Confidentiality != global::Sdmxdl.Format.Protobuf.ConfidentialityDto.Public) {
        Confidentiality = other.Confidentiality;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            names_.AddEntriesFrom(input, _map_names_codec);
            break;
          }
          case 26: {
            Driver = input.ReadString();
            break;
          }
          case 34: {
            Endpoint = input.ReadString();
            break;
          }
          case 42: {
            properties_.AddEntriesFrom(input, _map_properties_codec);
            break;
          }
          case 50: {
            aliases_.AddEntriesFrom(input, _repeated_aliases_codec);
            break;
          }
          case 58: {
            Website = input.ReadString();
            break;
          }
          case 66: {
            Monitor = input.ReadString();
            break;
          }
          case 74: {
            MonitorWebsite = input.ReadString();
            break;
          }
          case 80: {
            Confidentiality = (global::Sdmxdl.Format.Protobuf.ConfidentialityDto) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            names_.AddEntriesFrom(ref input, _map_names_codec);
            break;
          }
          case 26: {
            Driver = input.ReadString();
            break;
          }
          case 34: {
            Endpoint = input.ReadString();
            break;
          }
          case 42: {
            properties_.AddEntriesFrom(ref input, _map_properties_codec);
            break;
          }
          case 50: {
            aliases_.AddEntriesFrom(ref input, _repeated_aliases_codec);
            break;
          }
          case 58: {
            Website = input.ReadString();
            break;
          }
          case 66: {
            Monitor = input.ReadString();
            break;
          }
          case 74: {
            MonitorWebsite = input.ReadString();
            break;
          }
          case 80: {
            Confidentiality = (global::Sdmxdl.Format.Protobuf.ConfidentialityDto) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WebSourcesDto : pb::IMessage<WebSourcesDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WebSourcesDto> _parser = new pb::MessageParser<WebSourcesDto>(() => new WebSourcesDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WebSourcesDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SdmxdlWebReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSourcesDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSourcesDto(WebSourcesDto other) : this() {
      webSources_ = other.webSources_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WebSourcesDto Clone() {
      return new WebSourcesDto(this);
    }

    /// <summary>Field number for the "web_sources" field.</summary>
    public const int WebSourcesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Sdmxdl.Format.Protobuf.Web.WebSourceDto> _repeated_webSources_codec
        = pb::FieldCodec.ForMessage(10, global::Sdmxdl.Format.Protobuf.Web.WebSourceDto.Parser);
    private readonly pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.WebSourceDto> webSources_ = new pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.WebSourceDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.WebSourceDto> WebSources {
      get { return webSources_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WebSourcesDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WebSourcesDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!webSources_.Equals(other.webSources_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= webSources_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      webSources_.WriteTo(output, _repeated_webSources_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      webSources_.WriteTo(ref output, _repeated_webSources_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += webSources_.CalculateSize(_repeated_webSources_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WebSourcesDto other) {
      if (other == null) {
        return;
      }
      webSources_.Add(other.webSources_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            webSources_.AddEntriesFrom(input, _repeated_webSources_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            webSources_.AddEntriesFrom(ref input, _repeated_webSources_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MonitorReportDto : pb::IMessage<MonitorReportDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonitorReportDto> _parser = new pb::MessageParser<MonitorReportDto>(() => new MonitorReportDto());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonitorReportDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SdmxdlWebReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReportDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReportDto(MonitorReportDto other) : this() {
      _hasBits0 = other._hasBits0;
      source_ = other.source_;
      status_ = other.status_;
      uptimeRatio_ = other.uptimeRatio_;
      averageResponseTime_ = other.averageResponseTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReportDto Clone() {
      return new MonitorReportDto(this);
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 1;
    private string source_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Source {
      get { return source_; }
      set {
        source_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto status_ = global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "uptime_ratio" field.</summary>
    public const int UptimeRatioFieldNumber = 3;
    private readonly static double UptimeRatioDefaultValue = 0D;

    private double uptimeRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double UptimeRatio {
      get { if ((_hasBits0 & 1) != 0) { return uptimeRatio_; } else { return UptimeRatioDefaultValue; } }
      set {
        _hasBits0 |= 1;
        uptimeRatio_ = value;
      }
    }
    /// <summary>Gets whether the "uptime_ratio" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUptimeRatio {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "uptime_ratio" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUptimeRatio() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "average_response_time" field.</summary>
    public const int AverageResponseTimeFieldNumber = 4;
    private readonly static long AverageResponseTimeDefaultValue = 0L;

    private long averageResponseTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AverageResponseTime {
      get { if ((_hasBits0 & 2) != 0) { return averageResponseTime_; } else { return AverageResponseTimeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        averageResponseTime_ = value;
      }
    }
    /// <summary>Gets whether the "average_response_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAverageResponseTime {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "average_response_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAverageResponseTime() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonitorReportDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonitorReportDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Source != other.Source) return false;
      if (Status != other.Status) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UptimeRatio, other.UptimeRatio)) return false;
      if (AverageResponseTime != other.AverageResponseTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Source.Length != 0) hash ^= Source.GetHashCode();
      if (Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto.Unknown) hash ^= Status.GetHashCode();
      if (HasUptimeRatio) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UptimeRatio);
      if (HasAverageResponseTime) hash ^= AverageResponseTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Source.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Source);
      }
      if (Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (HasUptimeRatio) {
        output.WriteRawTag(25);
        output.WriteDouble(UptimeRatio);
      }
      if (HasAverageResponseTime) {
        output.WriteRawTag(32);
        output.WriteInt64(AverageResponseTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Source.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Source);
      }
      if (Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (HasUptimeRatio) {
        output.WriteRawTag(25);
        output.WriteDouble(UptimeRatio);
      }
      if (HasAverageResponseTime) {
        output.WriteRawTag(32);
        output.WriteInt64(AverageResponseTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Source.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Source);
      }
      if (Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (HasUptimeRatio) {
        size += 1 + 8;
      }
      if (HasAverageResponseTime) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AverageResponseTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonitorReportDto other) {
      if (other == null) {
        return;
      }
      if (other.Source.Length != 0) {
        Source = other.Source;
      }
      if (other.Status != global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto.Unknown) {
        Status = other.Status;
      }
      if (other.HasUptimeRatio) {
        UptimeRatio = other.UptimeRatio;
      }
      if (other.HasAverageResponseTime) {
        AverageResponseTime = other.AverageResponseTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Source = input.ReadString();
            break;
          }
          case 16: {
            Status = (global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto) input.ReadEnum();
            break;
          }
          case 25: {
            UptimeRatio = input.ReadDouble();
            break;
          }
          case 32: {
            AverageResponseTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Source = input.ReadString();
            break;
          }
          case 16: {
            Status = (global::Sdmxdl.Format.Protobuf.Web.MonitorStatusDto) input.ReadEnum();
            break;
          }
          case 25: {
            UptimeRatio = input.ReadDouble();
            break;
          }
          case 32: {
            AverageResponseTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MonitorReportsDto : pb::IMessage<MonitorReportsDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonitorReportsDto> _parser = new pb::MessageParser<MonitorReportsDto>(() => new MonitorReportsDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonitorReportsDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SdmxdlWebReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReportsDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReportsDto(MonitorReportsDto other) : this() {
      uriScheme_ = other.uriScheme_;
      reports_ = other.reports_.Clone();
      creationTime_ = other.creationTime_;
      expirationTime_ = other.expirationTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonitorReportsDto Clone() {
      return new MonitorReportsDto(this);
    }

    /// <summary>Field number for the "uri_scheme" field.</summary>
    public const int UriSchemeFieldNumber = 1;
    private string uriScheme_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UriScheme {
      get { return uriScheme_; }
      set {
        uriScheme_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reports" field.</summary>
    public const int ReportsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto> _repeated_reports_codec
        = pb::FieldCodec.ForMessage(18, global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto.Parser);
    private readonly pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto> reports_ = new pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Sdmxdl.Format.Protobuf.Web.MonitorReportDto> Reports {
      get { return reports_; }
    }

    /// <summary>Field number for the "creation_time" field.</summary>
    public const int CreationTimeFieldNumber = 3;
    private string creationTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CreationTime {
      get { return creationTime_; }
      set {
        creationTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expiration_time" field.</summary>
    public const int ExpirationTimeFieldNumber = 4;
    private string expirationTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExpirationTime {
      get { return expirationTime_; }
      set {
        expirationTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonitorReportsDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonitorReportsDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UriScheme != other.UriScheme) return false;
      if(!reports_.Equals(other.reports_)) return false;
      if (CreationTime != other.CreationTime) return false;
      if (ExpirationTime != other.ExpirationTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UriScheme.Length != 0) hash ^= UriScheme.GetHashCode();
      hash ^= reports_.GetHashCode();
      if (CreationTime.Length != 0) hash ^= CreationTime.GetHashCode();
      if (ExpirationTime.Length != 0) hash ^= ExpirationTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UriScheme.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UriScheme);
      }
      reports_.WriteTo(output, _repeated_reports_codec);
      if (CreationTime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CreationTime);
      }
      if (ExpirationTime.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExpirationTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UriScheme.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UriScheme);
      }
      reports_.WriteTo(ref output, _repeated_reports_codec);
      if (CreationTime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CreationTime);
      }
      if (ExpirationTime.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExpirationTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UriScheme.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UriScheme);
      }
      size += reports_.CalculateSize(_repeated_reports_codec);
      if (CreationTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreationTime);
      }
      if (ExpirationTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExpirationTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonitorReportsDto other) {
      if (other == null) {
        return;
      }
      if (other.UriScheme.Length != 0) {
        UriScheme = other.UriScheme;
      }
      reports_.Add(other.reports_);
      if (other.CreationTime.Length != 0) {
        CreationTime = other.CreationTime;
      }
      if (other.ExpirationTime.Length != 0) {
        ExpirationTime = other.ExpirationTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UriScheme = input.ReadString();
            break;
          }
          case 18: {
            reports_.AddEntriesFrom(input, _repeated_reports_codec);
            break;
          }
          case 26: {
            CreationTime = input.ReadString();
            break;
          }
          case 34: {
            ExpirationTime = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UriScheme = input.ReadString();
            break;
          }
          case 18: {
            reports_.AddEntriesFrom(ref input, _repeated_reports_codec);
            break;
          }
          case 26: {
            CreationTime = input.ReadString();
            break;
          }
          case 34: {
            ExpirationTime = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
